/// Artimech
/// 
/// Copyright © <2017> <George A Lancaster>
/// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
/// and associated documentation files (the "Software"), to deal in the Software without restriction, 
/// including without limitation the rights to use, copy, modify, merge, publish, distribute, 
/// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software 
/// is furnished to do so, subject to the following conditions:
/// The above copyright notice and this permission notice shall be included in all copies 
/// or substantial portions of the Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
/// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
/// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
/// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
/// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
/// OTHER DEALINGS IN THE SOFTWARE.

using UnityEngine;
using System.Collections;

namespace Artimech
{
    public class aMechThirdPersonCam : stateMachineGame
    {
        public GameObject m_TargetGoal;
        public GameObject m_TargetFollow;
        public GameObject m_Player;
        public GameObject m_CameraGoal;

        public float m_MinDistanceToPlayer = 4.0f;
        public float m_MaxDistanceToPlayer = 6.0f;
        public float m_MaxDistanceToTargetFollow;
        public float m_CameraFollowVelocity = 5.0f;
        public AnimationCurve m_CamApproachCurve;
        public float m_TargetFollowVelocity = 5.0f;
        public AnimationCurve m_TargetApproachCure;

        public float m_FollowToGoalCamVel = 5.0f;
        public AnimationCurve m_FollowToGoalCamApproachCure;

        [Header("Mouse cam move")]
        public float m_CamRotationVelX = 3.0f;
        public float m_CamRotationVelY = 3.0f;


        new void Awake()
        {
            base.Awake();
            CreateStates();
        }

        // Use this for initialization
        new void Start()
        {
            base.Start();
        }

        // Update is called once per frame
        new void Update()
        {
            base.Update();
        }

        new void FixedUpdate()
        {
            base.FixedUpdate();
        }

        /// <summary>
        /// Autogenerated state are created here inside this function.
        /// </summary>
        void CreateStates()
        {

            m_CurrentState = AddState(new camStart(this.gameObject), "camStart");

            //<ArtiMechStates>
            AddState(new camUpdate(this.gameObject), "camUpdate");

        }
    }
}